version: 2

mkdocs:
  configuration: mkdocs.yml
  fail_on_warning: false

build:
  image: latest

formats: all

python:
  version: 3.7
  install:
    - requirements: requirements/requirements.txt
    - method: pip
      path: .
