site_name: 'JumpServer 文档'
site_url: 'https://jumpserver.org'
site_description: 'JumpServer 文档'
site_author: 'wojiushixiaobai'

repo_name: 'GitHub Star'
repo_url: 'https://github.com/jumpserver/jumpserver'
edit_uri: ''

theme:
  name: 'material'
  logo: 'img/logo.png'
  favicon: 'img/facio.ico'
  language: 'zh'
  highlightjs: true
  feature:
    tabs: true
  hljs_languages:
    - yaml
    - django
  palette:
    primary: 'green'
    accent: 'red'
  features:
    - search.suggest
    - search.highlight

nav:
  - 总体介绍: index.md
  - 安装配置:
    - 极速部署: install/setup_by_fast.md
    - 安全建议: install/install_security.md
  - 管理文档:
    - 快速入门: admin-guide/quick_start.md
    - 更新升级:
        - 升级文档: admin-guide/upgrade/upgrade.md
    - 迁移文档: admin-guide/migration.md
    - 资产要求:
        - Tetnet: admin-guide/assets/telnet.md
        - Linux SSH: admin-guide/assets/linux_ssh.md
        - Linux VNC: admin-guide/assets/linux_vnc.md
        - Windows SSH: admin-guide/assets/windows_ssh.md
        - Windows VNC: admin-guide/assets/windows_vnc.md
        - Windows RDP: admin-guide/assets/windows_rdp.md
    - 应用要求:
        - MySQL: admin-guide/app/mysql.md
        - Kubernetes: admin-guide/app/kubernetes.md
    - 身份认证:
        - SSO: admin-guide/authentication/sso.md
        - CAS: admin-guide/authentication/cas.md
        - MFA: admin-guide/authentication/mfa.md
        - LDAP: admin-guide/authentication/ldap.md
        - OpenID: admin-guide/authentication/openid.md
        - Radius: admin-guide/authentication/radius.md
    - 反向代理: admin-guide/proxy.md
    - 参数说明: admin-guide/env.md
  - 开发文档:
    - API文档: dev/rest_api.md
  - 用户文档:
    - 我的资产: user-guide/assets/user-asset.md
    - 我的应用:
      - 数据库应用: user-guide/applications/user-database-app.md
    - 命令执行: user-guide/ops/command-executions/create.md
    - 个人信息: user-guide/users/profile.md
    - Web终端: user-guide/terminal/web-terminal.md
    - 文件管理: user-guide/terminal/web-sftp.md
  - 帮助文档:
    - 其他问题: faq/other.md
    - Core 常见问题: faq/core.md
    - Luna 常见问题: faq/luna.md
    - koko 常见问题: faq/koko.md
    - Guacamole 问题: faq/guacamole.md
  - 关于:
    - 贡献列表: about/contributor.md
    - 更新说明: about/change_log.md
    - 联系方式: about/contact.md
    - 商业产品: about/commercial.md
  - 企业版试用: enterprise.md

markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/jumpserver
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/r/jumpserver/

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/tablesort.min.js
  - javascripts/extra.js

copyright: Copyright &copy; 2014-2020 <a href="https://www.fit2cloud.com">杭州飞致云信息科技有限公司</a>, All Rights Reserved. <a href="http://www.beian.miit.gov.cn" target="_blank">京ICP备15023818号</a>
google_analytics: ['UA-147297392-3','docs.jumpserver.org']
plugins:
  - search
